---
title: "Orange County Air Pollution and Household Income"
format: html
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(sf)
library(here)
library(tmap)

```

```{r}
#| message: false
#| warning: false
# read in the the geodatabase 
ejscreen <- sf::st_read(here::here("data", "ejscreen", "EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb"))
```

```{r}
#| message: false
#| warning: false
# filter to only include the State and County of focus (Santa Ana) and multiple decimal point variable by 100 to see percentage point values

Orange_County <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "CA", CNTY_NAME %in% c("Orange County"))
Orange_County$LOWINCPCT <-Orange_County$LOWINCPCT * 100
```

```{r}
#| message: false
#| warning: false
# Map poor air quality, RSEI_AIR, within Orange County, with a color gradient system focused on different particulate levels.

tm_shape(Orange_County) +
  tm_polygons(fill = "RSEI_AIR",
              border.col = "black",
              palette = "Reds",
              title = "Air Pollution Index",
              breaks= c(0.00, 199.00, 399.00, 599.00, 799.0, 999.00, 1199.00, 2000.00, 3000.00, 5000.00, 10000.00, 15000.00)) + 
  tm_compass(position = c("left", "top"))+ 
  tm_scalebar(position = c("left", "bottom")) + 
  tm_layout(main.title = "Map of Areas With High Air Pollution")
```

```{r}
#| message: false
#| warning: false
# Map the percentage of low income designated households by zipcode to determine if there is a spatial correlation between income levels and hazardous air levels. 
tm_shape(Orange_County) +
tm_polygons(fill = "LOWINCPCT", 
            border.col = "black",
            breaks= c(0, 20, 40, 60, 80, 100),
            title = "% of HH Low Income") + 
  tm_compass(position = c("left", "top"))+ 
  tm_scalebar(position = c("left", "bottom")) + 
  tm_layout(main.title = "Map of Low Income Households")
```
